START TRANSACTION;

INSERT INTO role(id,name) VALUES (1, 'ROLE_ADMIN');
INSERT INTO role(id,name)  VALUES (2, 'ROLE_LECTURER');
INSERT INTO role(id,name)  VALUES (3, 'ROLE_STUDENT');
INSERT INTO role(id,name)  VALUES (4, 'ROLE_SUPER_ADMIN');

COMMIT;
